# 
# docker-compose -f docker-compose-no-app.yml up -d
# docker-compose run --service-ports mariadb -d
# docker run -d --rm --network="host" -p 3306:3306 -h 127.0.0.1 -e MYSQL_ROOT_PASSWORD=irol_root_pw --name mariadb mariadb:lts
version: '3'

services:
  mariadb:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: irol_root_pw
      MYSQL_USER:  irol 
      MYSQL_PASSWORD: irol_pw
#      MYSQL_ROOT_HOST: localhost
      MARIADB_AUTO_UPGRADE: 'false'
    expose:
        - "3306"
    ports:
        - "3306:3306"
    volumes: 
      - "./mariadb/data:/var/lib/mysql/data/"
      - "./mariadb/logs:/var/lib/mysql/logs/"
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306