# 
# docker-compose -f docker-compose-db.yml up -d
# docker-compose run --service-ports mariadb -d
# docker run -d --rm --network="host" -p 3306:3306 -h 127.0.0.1 -e MYSQL_ROOT_PASSWORD=irol_root_pw -v /db/init.sql:/tmp/init.sql -v /db/mariadb/data:/var/lib/mysql/data -v /logs/mariadb:/var/lib/mysql/logs --name mariadb mariadb:lts
# docker run -d --rm -p 3306:3306 -e MYSQL_ROOT_PASSWORD=irol_root_pw -v /db/init.sql:/tmp/init.sql -v /db/mariadb/data:/var/lib/mysql/data -v /logs/mariadb:/var/lib/mysql/logs --name mariadb mariadb:lts
version: '3'

services:
  mariadb:
    image: mariadb:lts
    restart: always
    env_file: '.env'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_HOST: localhost
      MARIADB_AUTO_UPGRADE: 'false'
    expose:
        - ${DB_PORT}
    ports:
        - "${DB_PORT}:3306"
    command: --init-file /tmp/init.sql
    volumes: 
      - "./db/init.sql:/tmp/init.sql"
      - "./db/mariadb/data:/var/lib/mysql/data/"
      - "./logs/mariadb:/var/lib/mysql/logs/"
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306