# 
# docker-compose -f docker-compose-only-db.yml up -d
# docker-compose run --service-ports mariadb -d
version: '3'
 
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file: '.env'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: ${DB_HOST}
      MARIADB_AUTO_UPGRADE: 'false'
    ports:
      - "3306:3306"
# открываем порт контейнера      
    expose: 
      - "3306"  
    volumes:
      - ./init.sql:/tmp/init.sql
      - ./mysql/:/var/lib/mysql/
      - ./my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/log/mysql/


